config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :description, presence: true, length: { minimum: 10, maximum: 100}
  validates :user_id, presence: true
end
#validations set for new article object instances. Must be present; length min/max set

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase } 
  #saves email in downcase
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            #ensures unique username + no case sense (joe = Joe = jOE)
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX} 
            #using regex for proper email address format
  has_secure_password          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # @current_user = @current_user || User.find....
  end 

  def logged_in?
    !!current_user 
    # bang bang is like asking true or false
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must log in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/article_categories_controller.rb
class ArticleCategoriesController < ApplicationController
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5) #standard pagination implementation
  end
  
  def show
    set_article
  end
  
  def edit
    set_article
  end
  
  def new
    @article = Article.new
  end
  
  def create
    #render plain: params[:article].inspect
    #This displays the params hash data in the browser
    @article = Article.new(article_params)
    @article.user = current_user
    #pulls the specified attributes from params with private method from bottom of page 
    if @article.save
      flash[:info] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render :new 
      #could also be 'new'
    end
  end
  
  def update
    set_article
    if @article.update(article_params)
      flash[:info] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end
  
  def destroy
    set_article
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end
  
  private
  
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
    #this is the secret method that stores the attributes we want to save and gets passed to the CREATE action.
  end
  
  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path 
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 10) #standard pagination implementation 
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:info] = "Category successfully created"
      redirect_to categories_path
    else
      render :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category successfully updated"
      redirect_to category_path(@category)
    else
      render :edit
    end
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      # if not logged in || logged in but not the admin
      flash[:danger] = "Only admin can perform that action"
      redirect_to categories_path
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
    
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
    # this validates whether defining 'user' was successful && authenticates it
      flash[:info] = "You have successfully logged in"
      redirect_to user_path(user)
    else   
      flash.now[:danger] = "There was a problem with your login attempt"
      render :new
    end    
  end
  
  def destroy
    session[:user_id] = nil
    # ends user session
    flash[:info] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end
  
  def edit 
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:info] = "Welcome to the conversation, #{@user.username}"
      redirect_to user_path(@user)
    else
      render :new
    end
  end
  
  def update
    if @user.update(user_params)
      flash[:info] = "Account successfully updated"
      redirect_to user_path
    else
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by the user have been deleted"
    redirect_to users_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])  
  end
  
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit your own profile"
      redirect_to user_path(current_user)
    end
  end
  
  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80}) #parameter 2 is the default size.  Override inline on user show page
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
    #this method can be found in Gravatar docs and is specific to Gravatar
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <p><b>Title: </b><%= link_to article.title, article_path(article), class: 'article-link' %></p>
        </div>
        <div class="article-body">
          <p><b>Description: </b><%= truncate(article.description, length: 100) %></p> <!--truncate displays the amount of characters specified by length-->
          <div class='article-index-meta'>
            <small>Created by: <% if article.user %>
                                 <%= article.user.username %>
                               <% else %>
                                 <i>unknown</i>
                               <% end %>   
                               <%= time_ago_in_words(article.created_at) %> ago, last updated: 
                               <%= time_ago_in_words(article.updated_at) %> ago </small>
          </div>                   
        </div> 
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
          <!--render article.categories references viewa/categories/_category.html.erb-->
        <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete", article_path(article), method: :delete, 
                        data: { confirm: "Are you sure?" },
                        class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>  
      </div>
    </div>
  </div>  
<% end %>

app/views/articles/_form.html.erb
<%= render "share/errors", {obj: @article} %>


<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %><!--form class="form-horizontal">-->
      <div class="form-group">
        <div class="control-label col-sm-2"><!--<label for="inputEmail3" class="col-sm-2 control-label">Email</label>-->
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %><!--<input type="email" class="form-control" id="inputEmail3" placeholder="Email">-->
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description", autofocus: true %>
        </div>  
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
            <!--creates checkboxes-->
          </div>
        </div>  
      </div>
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-primary btn-lg" %>
          </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [<%= link_to "Cancel request and return to articles listing", articles_path %>]
    </div>
  </div>  
</div>
<!--FOR NEW.HTML.ERB: articles/new.html.erb form.  This data stored in params and sent through CREATE action via POST-->
<!--FOR EDIT.HTML.ERB: articles/edit.html.erb form.  Edit this data, from params and submitted via PATCH-->

app/views/articles/edit.html.erb
<h2 align="center">Edit an article</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<h3 align="center">Articles</h3>


<div align="center">
  <%= will_paginate %>
</div>  
<!--Adds per page navigation-->

<%= render 'article', obj: @articles %>
<!--Within the article partial, the article variable will refer to @articles.-->

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h2 align="center">Create an article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title:   <i><%= @article.title %></i></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row art-show-row" align="center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by:</li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <!--gravatar image as link to users show page-->
          <li class="article-title user-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
          <!--pluralize displays the number and pluralizes the keyword when necessary-->
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description" align="center"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
    <!--render @article.categories references viewa/categories/_category.html.erb-->
  <% end %>
  <div class="article-actions">
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-primary" %>
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete, 
                  data: { confirm: "Are you sure?" },
                  class: "btn btn-xs btn-danger" %>
    <% end %>              
  </div>
</div>  

app/views/categories/_category.html.erb
<span class="badge category-badge"><%= link_to category.name, category_path(category), class: 'category-name-badge' %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render "share/errors", {obj: @category} %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
  [<%= link_to "Cancel request and return to articles listing", articles_path %>]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Update Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h2 align="center">All Categories</h2>


<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <div class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category), class: 'article-link' %>
            <!--category_path == show page-->
          </li>
          <li>
            <small><p><%= pluralize(category.articles.count, "article") %></p></small>
          </li>
        </div>
      </div>
    </div>  
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create New Category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<h3 align="center"><%= "Category: " + @category.name %></h3>


<div align="center">
  <% if logged_in? && current_user.admin? %>
    <div>
      <span class="badge cat-show-badge"><%= link_to "Edit Category Name", category_path(@category), class: 'category-name-badge' %></span>
    </div>
  <% end %>  
  <%= will_paginate @category_articles %>
</div>  
<!--Adds per page navigation-->

<%= render 'articles/article', obj: @category_articles %>
<!--Within the article partial, the article variable will refer to all the articles for a given category.-->

<div align="center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container footer-container">
    <small class="credits">
      <span><p class="fp1">&copy<b>ATLAS</b>:  <b>A</b>nother <b>T</b>witter <b>L</b>ook<b>A</b>like <b>S</b>ite</p><p><%= link_to "Brandon S Brigance", 'https://bsb.netlify.com/', class: "fp2" %></p></span>
    </small>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'><!--the alert-type determines bootstrap alert color.  Here we pass :notice from the article controller-->
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>  
    <% end %>
  </div>
</div>  
<!--this flash block will render flash messages when called in a template-->

app/views/layouts/_navigation.html.erb
<!--<nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display 
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <ul><*****link_to path*****</ul>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling 
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>*****link_to path******</li>
          <li>*****link_to path******</li>
          <li><a href="#">CONTACT</a></li>
        </ul>
      </div>
      <!-- /.navbar-collapse 
    </div>
          <!-- /.container-fluid
  </nav><!--Nav ends-->
  
  
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ATL@S", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Explore/Create<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Create an article', new_article_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'All Categories', categories_path %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>   
              <% if logged_in? && current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create a category", new_category_path %></li>
              <% end %>  
            </ul>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Explore <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'All Categories', categories_path %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>    
            </ul>
          </li>
        <% end %>  
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Profile <%=": Admin" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View your profile", user_path(current_user) %><li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li> 
          <li><%= link_to 'Sign-up', signup_path %></li>
        <% end %>    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div id="wrap">
    
    <%= render 'layouts/navigation' %>
    
    <div class="container content-container">
      
      <%= render 'layouts/messages' %>
      <%= yield %> <!--views render here-->
      
    </div>  
    
  </div><!--Wrap ends-->
  <!--%= debug(params) if Rails.env.development? %> <!--This provides MVC data in the browser/ helps with errors-->
  <%= render 'layouts/footer' %>  
  
 
</body>
</html>

app/views/pages/about.html.erb
<div id="about-wrap">
  
  <div class="jumbotron jumbo-about">
    <div class="about-headline">
      <h1 class="about-text">Hello.</h1>
      <p class="about-text">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.<span>|</span></p>
    </div> 
  </div>   
  
</div>

app/views/pages/home.html.erb
<div id="home-wrap">
  <div class="jumbotron-wrap"><!--image-->
    <div class="jumbotron jumbotron-home" id="jumbo-home-background">
      <div class="jumbo-text">
        <h1 class="jumbo-one">ATLAS</h1>
        <h3 class="jumbo-two"><b>A</b>nother <b>T</b>witter <b>L</b>ook<b>A</b>like <b>S</b>ite</h3>
      </div>
     
    </div>
  </div>
  
  
  <div class="row-fluid home-rows">
    <div align="center">
      <% if !logged_in? %>
        <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-lg btn-xlarge home-jumbo" %>
      <% end %>
    </div>
  </div>
</div>  
  

app/views/share/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger"><!--sets red alert color-->
        <div class="panel-heading">
          <h2 class="panel-title"> 
            <%= pluralize(obj.errors.count, "error") %><!--method to display 'error' or 'errors' based on count-->
            Prohibited this article from being saved: <!--message header-->
          </h2>
          <div class="panel-body"><!--block body/ main-->
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>  
        </div>
      </div>
    </div>
  </div>
<% end %>  
<!--if errors occur based on validations, will return those errors as message-->

app/views/users/_form.html.erb
<%= render "share/errors", {obj: @user} %>


<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %><!--form class="form-horizontal">-->
      <div class="form-group">
        <div class="control-label col-sm-2"><!--<label for="inputEmail3" class="col-sm-2 control-label">Email</label>-->
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter user name", autofocus: true %><!--<input type="email" class="form-control" id="inputEmail3" placeholder="Email">-->
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>  
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
          <!--'password' is the virtual attribute of 'password_digest'-->
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>  
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit( @user.new_record? ? 'Sign up' : 'Update', class: "btn btn-primary btn-lg") %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [<%= link_to "Cancel request and return to articles listing", articles_path %>]
    </div>
  </div>  
</div>

<!-- f.submit 'Sign up', class: "btn btn-primary btn-lg" %>

app/views/users/edit.html.erb
<h1 align="center">Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align='center'>Users</h1>


<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <!--gravatar image as link to users show page-->
          <li class="article-title user-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
          <!--pluralize displays the number and pluralizes the keyword when necessary-->
          <% if logged_in? && current_user.admin? %>
            <li><%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user and all their articles?" } %></li>
          <% end %>
        </div>
      </div>
    </ul>  
  <% end %>  
  <%= will_paginate %> <!--Adds per page navigation-->
</div> 

app/views/users/new.html.erb
<h1 align="center">Sign-up for Atlas</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"><%= @user.username %></h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4" align="center">
    <%= gravatar_for @user, size: 170 %>
    <!--size: 150 overrides the default size called in the gravatar method @ application_helpers.rb-->
  </div>
</div>  
<h4 align="center"><%= @user.username %>'s articles</h4>

<div align="center">
  <%= will_paginate @user_articles %>
</div>

<%= render 'articles/article', obj: @user_articles %>

<div align="center">
  <%= will_paginate @user_articles %>
</div>